stages:
    - PreProcess
    - BakeMalware
    - PostProcess

workflow:
    rules:
        - changes:
            - shellcode/*

PreProcess:
    stage: PreProcess
    tags:
        - maas
    script:
        - |
            [ -f "/payloads/.lib/garble" ] && exit
            mkdir -p /payloads/.lib
            export GOBIN=/payloads/.lib
            go install mvdan.cc/garble@latest

ScareCrow:
    stage: BakeMalware
    tags:
        - maas
    script:
        - |
            cd /payloads
            ScareCrow -I $CI_PROJECT_DIR/shellcode/notepad_x64.bin -Loader binary -nosign

PostProcess:
    stage: PostProcess
    tags:
        - maas
    script:
        - |
            echo "Creating ZIP file"
