stages:
    - BakeMalware
    - PostProcess

workflow:
    rules:
        - changes:
            - shellcode/*

ScareCrow:
    stage: BakeMalware
    tags:
        - maas
    script:
        - |
            cd /payloads
            ScareCrow -I $CI_PROJECT_DIR/shellcode/notepad_x64.bin -Loader binary -nosign
            ls -al /runner
            ls -al /payloads

ZipFiles:
    stage: PostProcess
    tags:
        - maas
    script:
        - |
            echo "Creating ZIP file"
