stages:
    - PreProcess
    - BakeMalware
    - PostProcess

workflow:
    rules:
        - changes:
            - shellcode/*

PreProcess:
    stage: PreProcess
    tags:
        - maas
    script:
        - export PATH=$PATH:${CI_PROJECT_DIR}/bin
        - mkdir -p /payloads/${CI_COMMIT_SHORT_SHA}/.lib
        - ln -f -s /usr/local/bin/garble /payloads/${CI_COMMIT_SHORT_SHA}/.lib/garble
        - ScareCrow_Pipeline.py -c ${CI_PROJECT_DIR}/SampleConfig.yml >.scarecrow.yml
    artifacts:
        paths:
            - .scarecrow.yml

ScareCrow:
    stage: BakeMalware
    trigger:
        include:
        - artifact: .scarecrow.yml
          job: PreProcess
        strategy: depend

PostProcess:
    stage: PostProcess
    tags:
        - maas
    script:
        - |
            DEST=${CI_PROJECT_DIR}/ScareCrowPayloads
            rm -rf /payloads/${CI_COMMIT_SHORT_SHA}/.lib
            cd /payloads
            7z a "${DEST}/${CI_COMMIT_SHORT_SHA}.7z" "${CI_COMMIT_SHORT_SHA}/*" -p"infected"
            rm -rf /payloads/${CI_COMMIT_SHORT_SHA}
    artifacts:
        name: ScareCrowPayloads
        paths:
            - ScareCrowPayloads/
        expire_in: 1 day

